name: Deploy server

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on:
            ubuntu-latest
        container:
          image: node:22

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                node-version: 22

            - name: Install Dependencies 
              run: npm ci

            - name: Run tests
              run: npm run test

            - name: Build App
              run: npm run build

            - name: Print a message asking to deploy
              run: echo "Write actions to deploy me!"
