name: Deploy server

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on:
            ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                node-version: 22
                cache: 'npm'

            - name: Install Dependencies 
              run: npm ci

            - name: Run tests
              run: npm run test

            - name: Build App
              run: npm run build
    
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print a message
              run: echo Write actions to deploy me!
